# package build command:
# docker run --rm -v "$PWD":/usr/src  timeswipe:deb /usr/src/build_deb.sh
FROM ubuntu:19.10

RUN apt-get -y update && DEBIAN_FRONTEND=noninteractive apt -y install binutils-aarch64-linux-gnu g++-aarch64-linux-gnu gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf make cmake gcc g++ libboost-all-dev





