name: Doxygen documentation for b1.2.1
on:
  push:
    branches:
      - b1.2.1
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Doxygen Action
      uses: mattnotmitt/doxygen-action@v1.2.0
      with:
        doxyfile-path: "Doxyfile" # default is ./Doxyfile
        working-directory: "doc/driver" # default is .
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # Default Doxyfile build documentation to html directory.
        # Change the directory if changes in Doxyfile
        publish_dir: doc/driver/doxygen/html
        destination_dir: b121
